version: '3'

services:
  jupyterhub:
    build: jupyterhub
    image: jupyterhub_img
    container_name: jupyterhub
    expose:
      - 8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#      - /var/data/jupyterhub:/srv/jupyterhub
    environment:
      - DOCKER_JUPYTER_CONTAINER=jupyterlab_img
      - DOCKER_NETWORK_NAME=traefik
      - HUB_IP=jupyterhub
      - HOST
      - JUPYTERHUB_CRYPT_KEY=${JUPYTERHUB_CRYPT_KEY}
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}-core.rule=PathPrefix(`/newhub`)
      
    restart: on-failure

  jupyterlab:
    build:
      context: jupyterlab
      args:
        NB_USER: jupyter
    image: jupyterlab_img
    container_name: jupyterlab-throaway
    network_mode: none
    command: echo

  #reverse-proxy:
    #image: traefik
    #container_name: reverse-proxy
    #ports:
      #- "80:80"
      #- "443:443"
      #- "8080:8080"
    #volumes:
      #- ./reverse-proxy/traefik.toml:/etc/traefik/traefik.toml
      #- /etc/certs:/etc/certs
      #- /var/run/docker.sock:/var/run/docker.sock
    #restart: on-failure

networks:
  traefik:
    name: traefik